/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedClusterRouteImport } from './routes/_authenticated/cluster'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPoolRouteImport } from './routes/_authenticated/pool'
import { Route as AuthenticatedProtocolRouteImport } from './routes/_authenticated/protocol'
import { Route as AuthenticatedProxiesRouteImport } from './routes/_authenticated/proxies'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWrapRouteImport } from './routes/_authenticated/wrap'
import { Route as AuthenticatedLoadtestIndexRouteImport } from './routes/_authenticated/loadtest/index'
import { Route as AuthenticatedLoadtestTabRouteImport } from './routes/_authenticated/loadtest/$tab'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsTabRouteImport } from './routes/_authenticated/settings/$tab'
import { Route as AuthenticatedVmIndexRouteImport } from './routes/_authenticated/vm/index'
import { Route as AuthenticatedVmIdRouteImport } from './routes/_authenticated/vm/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClusterRoute = AuthenticatedClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolRoute = AuthenticatedPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolRoute = AuthenticatedProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProxiesRoute = AuthenticatedProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWrapRoute = AuthenticatedWrapRouteImport.update({
  id: '/wrap',
  path: '/wrap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoadtestIndexRoute =
  AuthenticatedLoadtestIndexRouteImport.update({
    id: '/loadtest/',
    path: '/loadtest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoadtestTabRoute =
  AuthenticatedLoadtestTabRouteImport.update({
    id: '/loadtest/$tab',
    path: '/loadtest/$tab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTabRoute =
  AuthenticatedSettingsTabRouteImport.update({
    id: '/settings/$tab',
    path: '/settings/$tab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVmIndexRoute = AuthenticatedVmIndexRouteImport.update({
  id: '/vm/',
  path: '/vm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVmIdRoute = AuthenticatedVmIdRouteImport.update({
  id: '/vm/$id',
  path: '/vm/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api': typeof AuthenticatedApiRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cluster': typeof AuthenticatedClusterRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/import': typeof AuthenticatedImportRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/pool': typeof AuthenticatedPoolRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/system': typeof AuthenticatedSystemRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wrap': typeof AuthenticatedWrapRoute
  '/loadtest/$tab': typeof AuthenticatedLoadtestTabRoute
  '/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/vm/$id': typeof AuthenticatedVmIdRoute
  '/loadtest/': typeof AuthenticatedLoadtestIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/vm/': typeof AuthenticatedVmIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api': typeof AuthenticatedApiRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cluster': typeof AuthenticatedClusterRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/import': typeof AuthenticatedImportRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/pool': typeof AuthenticatedPoolRoute
  '/protocol': typeof AuthenticatedProtocolRoute
  '/proxies': typeof AuthenticatedProxiesRoute
  '/system': typeof AuthenticatedSystemRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wrap': typeof AuthenticatedWrapRoute
  '/': typeof AuthenticatedIndexRoute
  '/loadtest/$tab': typeof AuthenticatedLoadtestTabRoute
  '/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/vm/$id': typeof AuthenticatedVmIdRoute
  '/loadtest': typeof AuthenticatedLoadtestIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/vm': typeof AuthenticatedVmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cluster': typeof AuthenticatedClusterRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/pool': typeof AuthenticatedPoolRoute
  '/_authenticated/protocol': typeof AuthenticatedProtocolRoute
  '/_authenticated/proxies': typeof AuthenticatedProxiesRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wrap': typeof AuthenticatedWrapRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/loadtest/$tab': typeof AuthenticatedLoadtestTabRoute
  '/_authenticated/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/_authenticated/vm/$id': typeof AuthenticatedVmIdRoute
  '/_authenticated/loadtest/': typeof AuthenticatedLoadtestIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/vm/': typeof AuthenticatedVmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api'
    | '/billing'
    | '/cluster'
    | '/database'
    | '/import'
    | '/keys'
    | '/logs'
    | '/models'
    | '/overview'
    | '/pool'
    | '/protocol'
    | '/proxies'
    | '/system'
    | '/usage'
    | '/users'
    | '/wrap'
    | '/loadtest/$tab'
    | '/settings/$tab'
    | '/vm/$id'
    | '/loadtest/'
    | '/settings/'
    | '/vm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api'
    | '/billing'
    | '/cluster'
    | '/database'
    | '/import'
    | '/keys'
    | '/logs'
    | '/models'
    | '/overview'
    | '/pool'
    | '/protocol'
    | '/proxies'
    | '/system'
    | '/usage'
    | '/users'
    | '/wrap'
    | '/'
    | '/loadtest/$tab'
    | '/settings/$tab'
    | '/vm/$id'
    | '/loadtest'
    | '/settings'
    | '/vm'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/api'
    | '/_authenticated/billing'
    | '/_authenticated/cluster'
    | '/_authenticated/database'
    | '/_authenticated/import'
    | '/_authenticated/keys'
    | '/_authenticated/logs'
    | '/_authenticated/models'
    | '/_authenticated/overview'
    | '/_authenticated/pool'
    | '/_authenticated/protocol'
    | '/_authenticated/proxies'
    | '/_authenticated/system'
    | '/_authenticated/usage'
    | '/_authenticated/users'
    | '/_authenticated/wrap'
    | '/_authenticated/'
    | '/_authenticated/loadtest/$tab'
    | '/_authenticated/settings/$tab'
    | '/_authenticated/vm/$id'
    | '/_authenticated/loadtest/'
    | '/_authenticated/settings/'
    | '/_authenticated/vm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cluster': {
      id: '/_authenticated/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof AuthenticatedClusterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pool': {
      id: '/_authenticated/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof AuthenticatedPoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocol': {
      id: '/_authenticated/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof AuthenticatedProtocolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxies': {
      id: '/_authenticated/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof AuthenticatedProxiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wrap': {
      id: '/_authenticated/wrap'
      path: '/wrap'
      fullPath: '/wrap'
      preLoaderRoute: typeof AuthenticatedWrapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loadtest/': {
      id: '/_authenticated/loadtest/'
      path: '/loadtest'
      fullPath: '/loadtest/'
      preLoaderRoute: typeof AuthenticatedLoadtestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loadtest/$tab': {
      id: '/_authenticated/loadtest/$tab'
      path: '/loadtest/$tab'
      fullPath: '/loadtest/$tab'
      preLoaderRoute: typeof AuthenticatedLoadtestTabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/$tab': {
      id: '/_authenticated/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof AuthenticatedSettingsTabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vm/': {
      id: '/_authenticated/vm/'
      path: '/vm'
      fullPath: '/vm/'
      preLoaderRoute: typeof AuthenticatedVmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vm/$id': {
      id: '/_authenticated/vm/$id'
      path: '/vm/$id'
      fullPath: '/vm/$id'
      preLoaderRoute: typeof AuthenticatedVmIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedClusterRoute: typeof AuthenticatedClusterRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPoolRoute: typeof AuthenticatedPoolRoute
  AuthenticatedProtocolRoute: typeof AuthenticatedProtocolRoute
  AuthenticatedProxiesRoute: typeof AuthenticatedProxiesRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWrapRoute: typeof AuthenticatedWrapRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLoadtestTabRoute: typeof AuthenticatedLoadtestTabRoute
  AuthenticatedSettingsTabRoute: typeof AuthenticatedSettingsTabRoute
  AuthenticatedVmIdRoute: typeof AuthenticatedVmIdRoute
  AuthenticatedLoadtestIndexRoute: typeof AuthenticatedLoadtestIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedVmIndexRoute: typeof AuthenticatedVmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedClusterRoute: AuthenticatedClusterRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPoolRoute: AuthenticatedPoolRoute,
  AuthenticatedProtocolRoute: AuthenticatedProtocolRoute,
  AuthenticatedProxiesRoute: AuthenticatedProxiesRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWrapRoute: AuthenticatedWrapRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLoadtestTabRoute: AuthenticatedLoadtestTabRoute,
  AuthenticatedSettingsTabRoute: AuthenticatedSettingsTabRoute,
  AuthenticatedVmIdRoute: AuthenticatedVmIdRoute,
  AuthenticatedLoadtestIndexRoute: AuthenticatedLoadtestIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedVmIndexRoute: AuthenticatedVmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
